set ApiKey reason when setting to permanent fail
ApiKey no has a reason field in order to make it easier to distinguish between updaters that have been automatically shut down due to oauth needing a reauth or because of some other condition that is deemed to be hopeless wrt to getting the updater to a healthy state again.
Several such conditions are enumerated in ApiKey's PermanentFailReason inner class:
CLIENT_ERROR: typically an http 4xx type error
SERVER_EXCEPTION: PersistenceException or exception in the org.springframework root package qualify here
MANUAL_INTERVENTION: use of the admin interface to manually set a connector to permanent fail
UNKNOWN: server complaining in a non standard way